import React from 'react'
import { Metadata } from 'next/types'
import { Pixelify_Sans } from 'next/font/google';


export const metadata: Metadata = {
    title: "Login dulu dek",
    description: "Generated by create next app",
  };

 const pixelify = Pixelify_Sans({subsets: ["latin"]}); 

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div className={`${pixelify.className}`}>
        {children}
    </div>
  )
}
